url: "https://tehbrian.xyz" # the base hostname & protocol for your site

plugins:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag

collections:
    authors:
        output: true

defaults:
    - scope:
          path: ""
      values:
          layout: "default"
